### ISSUE TITLE
[openapi-alps] "rush deploy" fails with latest version of rush

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#7127]
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8514831&view=logs&j=d6cab82e-c36d-5e2e-17ab-85c68fa424d7&t=7029b4af-31d0-572d-2723-ad408d209dcc

**Comment by konrad-jamrozik** [comment]
The linked error pertains to missing bindings which should have been addressed by:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps/pullRequest/520946#1705106494

**Comment by mikeharder** [comment]
Latest error:

```
~/openapi-alps$ rush deploy -s openapi-kebab --overwrite

Rush Multi-Project Build Tool 5.113.4 - https://rushjs.io
Node.js version is 20.11.0 (LTS)

Starting "rush deploy"

Loading deployment scenario: /home/mharder/openapi-alps/common/config/rush/deploy-openapi-kebab.json
Extracting to target folder:  /home/mharder/openapi-alps/common/deploy
Main project for extraction: openapi-kebab
Analyzing project: openapi-kebab

ERROR: Cannot find package "nan" from "/home/mharder/openapi-alps/common/temp/node_modules/.pnpm/dtrace-provider@0.8.8/node_modules/dtrace-provider": Error:Cannot find module 'nan/' from '/home/mharder/openapi-alps/common/temp/node_modules/.pnpm/dtrace-provider@0.8.8/node_modules/dtrace-provider'
```

When using `rush@5.97.1`, the folder `common/temp/node_modules/.pnpm/nan@2.16.0` exists.  When using `rush@5.113.4`, it does not.  I believe this package is an optional dependency (directly or transitively), and `rush` made a change in `5.98.0` where the dependency is not installed but `rush deploy` still expects it to be available.

The workaround should be to add any missing dependencies to the nearest parent package in openapi-alps.

**Comment by mikeharder** [comment]
Verified this scenario works with `rush@5.113.4` on latest in `openapi-alps`.

**Comment by mikeharder** [comment]
I suspect this error was caused by the CI step "Cache PNPM packages" restoring the wrong packages (the cache key may be under-specified)

**Comment by mikeharder** [comment]
Repros reliably in this PR, but I have no idea why the small changes in this PR could trigger this again:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9969612&view=results

**Comment by mikeharder** [comment]
I believe this can fail intermittently, due to a race condition in rush and/or pnpm, where the optional dependency `nan` is sometimes treated as required.

A fix/workaround is to add `nan` as a direct dependency of `pipeline-bot`.
